import { DialogueNode } from '../types/game';

export const GAME_DIALOGUES: Record<string, DialogueNode> = {
  // --- PROLOGUE & KIKI ---
  intro_start: {
    id: 'intro_start',
    speaker: 'Narator Cerita',
    speakerRole: 'Lembah Nada Rasa',
    portrait: 'narrator',
    text: 'Langit bergemuruh pelan... Tiba-tiba kabut abu-abu pekat turun menyelimuti Lembah Nada Rasa! Air mancur terhenti, dan warna-warni bunga seketika memudar menjadi kelabu.',
    nextId: 'intro_start_2',
  },
  intro_start_2: {
    id: 'intro_start_2',
    speaker: 'Ezzel',
    speakerRole: 'Murid Petualang Kelas 4',
    portrait: 'player',
    text: 'Hah?! Apa yang terjadi pada desa kita? Lihat, ada benda berkilau yang jatuh di depanku... ini seperti Kompas Kristal bertuliskan "KOMPAS HATI"!',
    nextId: 'intro_start_3',
  },
  intro_start_3: {
    id: 'intro_start_3',
    speaker: 'Pesan Rahasia Kompas',
    speakerRole: 'Pusaka Lembah',
    portrait: 'compass_item',
    text: '"Warna dunia memudar saat hati terkunci oleh salah paham. Gunakan Kompas Resonansi untuk membaca perasaan sejati yang tersembunyi di balik kata-kata!"',
    choices: [
      {
        id: 'c_start_help',
        text: 'Tekan Kompas dan hampiri Kiki si Tupai!',
        impactScore: 10,
        resultDialogueId: 'kiki_wait',
      },
    ],
  },
  kiki_wait: {
    id: 'kiki_wait',
    speaker: 'Petunjuk Awal',
    speakerRole: 'Misi Pertama',
    portrait: 'narrator',
    text: 'Kiki si tupai pos melompat panik di sebelah kiri air mancur! Dekati dia lalu tekan tombol [RESONANSI EMOSI] untuk membaca apa yang sedang dirasakannya.',
  },

  // Kiki dialogue
  kiki_intro: {
    id: 'kiki_intro',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Ciiit! Gawat! Bencana besar! Surat-surat kiriman warga terbang tertiup angin kabut! Aku... aku pasti akan dimarahi! Semua orang akan membenciku!',
    thoughtBubble: 'Jantungku berdegup kencang sekali, nafasku rasanya sesak... aku takut gagal!',
    emotionAura: 'cemas',
    choices: [
      {
        id: 'c_kiki_1',
        text: 'Tenang Kiki, jangan teriak-teriak begitu, bikin pusing!',
        impactScore: -5,
        resultDialogueId: 'kiki_dismiss',
      },
      {
        id: 'c_kiki_2',
        text: 'Tenang Kiki, ayo kita menenangkan diri dulu.',
        impactScore: 15,
        resultDialogueId: 'kiki_calm_options',
      },
      {
        id: 'c_kiki_3',
        text: 'Wajar kamu merasa panik, tapi surat yang jatuh bisa kita kumpulkan bersama.',
        impactScore: 10,
        resultDialogueId: 'kiki_validate',
      },
    ],
  },
  kiki_dismiss: {
    id: 'kiki_dismiss',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Huuu... kamu malah menyalahkanku! Aku semakin gemetar...',
    nextId: 'kiki_intro',
  },
  kiki_validate: {
    id: 'kiki_validate',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Kamu... kamu tidak memarahiku? Tapi dadaku masih berdebar kencang sekali... rasanya seperti mau meledak.',
    nextId: 'kiki_calm_options',
  },
  kiki_calm_options: {
    id: 'kiki_calm_options',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Huhu... iya Ezzel, terima kasih sudah peduli. Tapi bagaimana caranya? Dadaku berdebar kencang sekali dan tubuhku gemetaran... Cara apa yang bisa membantuku tenang?',
    thoughtBubble: 'Aku ingin tenang, tapi aku butuh panduan sahabatku untuk meredakan kepanikan ini...',
    emotionAura: 'cemas',
    choices: [
      {
        id: 'c_kiki_reg_breathing',
        text: '🌬️ Teknik Napas Balon (4-4-4): Tarik napas pelan lewat hidung, tahan, lalu hembuskan.',
        impactScore: 20,
        resultDialogueId: 'kiki_prep_breathing',
      },
      {
        id: 'c_kiki_reg_grounding',
        text: '👁️ Grounding Panca Indra (5-4-3-2-1): Amati sekeliling agar pikiran kembali fokus.',
        impactScore: 20,
        resultDialogueId: 'kiki_prep_grounding',
      },
      {
        id: 'c_kiki_reg_stop',
        text: '🛑 Metode S.T.O.P: Berhenti sejenak, ambil napas jeda, amati perasaan, lalu bertindak.',
        impactScore: 20,
        resultDialogueId: 'kiki_prep_stop',
      },
      {
        id: 'c_kiki_reg_shakeout',
        text: '⚡ Shake-Out Tubuh: Goyangkan tangan, kaki, dan ekor untuk melepas ketegangan.',
        impactScore: 20,
        resultDialogueId: 'kiki_prep_shakeout',
      },
    ],
  },
  kiki_prep_breathing: {
    id: 'kiki_prep_breathing',
    speaker: 'Ezzel',
    speakerRole: 'Karakter Utama (Sahabat Empati)',
    portrait: 'player',
    text: 'Ayo Kiki, kita lakukan bersama! Tarik napas perlahan lewat hidung 4 detik, bayangkan ada balon mengembang di perut, tahan sebentar, lalu hembuskan perlahan.',
    triggerBreathing: true,
    triggerRegulationMode: 'breathing',
    nextId: 'kiki_after_breathing',
  },
  kiki_prep_grounding: {
    id: 'kiki_prep_grounding',
    speaker: 'Ezzel',
    speakerRole: 'Karakter Utama (Sahabat Empati)',
    portrait: 'player',
    text: 'Ayo Kiki, kita gunakan teknik Grounding 5-4-3-2-1! Amati benda di sekitar alun-alun: apa yang bisa kamu lihat, sentuh, dan dengar agar pikiranmu kembali tenang dan fokus.',
    triggerBreathing: true,
    triggerRegulationMode: 'grounding',
    nextId: 'kiki_after_grounding',
  },
  kiki_prep_stop: {
    id: 'kiki_prep_stop',
    speaker: 'Ezzel',
    speakerRole: 'Karakter Utama (Sahabat Empati)',
    portrait: 'player',
    text: 'Ayo terapkan metode S.T.O.P, Kiki! Stop (berhenti panik), Take a breath (ambil napas jeda), Observe (amati perasaan cemas tanpa takut), lalu Proceed (lanjutkan mencari surat dengan tenang).',
    triggerBreathing: true,
    triggerRegulationMode: 'stop',
    nextId: 'kiki_after_stop',
  },
  kiki_prep_shakeout: {
    id: 'kiki_prep_shakeout',
    speaker: 'Ezzel',
    speakerRole: 'Karakter Utama (Sahabat Empati)',
    portrait: 'player',
    text: 'Ayo Kiki, saat cemas otot kita menegang! Goyangkan kedua tanganmu, kibaskan kakimu, dan goyangkan ekormu untuk membuang rasa kaku dan hormon stres dari tubuh!',
    triggerBreathing: true,
    triggerRegulationMode: 'shakeout',
    nextId: 'kiki_after_shakeout',
  },
  kiki_breathe_prep: {
    id: 'kiki_breathe_prep',
    speaker: 'Ezzel',
    speakerRole: 'Karakter Utama (Sahabat Empati)',
    portrait: 'player',
    text: 'Ayo Kiki, kita lakukan bersama! Tarik napas perlahan lewat hidung 4 detik, bayangkan meniup balon di perut, tahan sebentar, lalu hembuskan perlahan.',
    triggerBreathing: true,
    triggerRegulationMode: 'breathing',
    nextId: 'kiki_after_breathing',
  },
  kiki_after_breathe: {
    id: 'kiki_after_breathe',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Fiuuuh... ajaib! Detak jantungku mulai melambat. Otakku terasa lebih jernih sekarang! Terima kasih sudah membimbingku menenangkan diri, Ezzel!',
    emotionAura: 'tenang',
    triggerColorRestoreZone: 'plaza',
    triggerQuestProgress: 'quest_start',
    nextId: 'kiki_reward',
  },
  kiki_after_breathing: {
    id: 'kiki_after_breathing',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Fiuuuh... ajaib! Detak jantungku mulai melambat. Otakku terasa lebih jernih dan nafasku kembali lega! Terima kasih sudah menemaniku teknik napas balon, Ezzel!',
    emotionAura: 'tenang',
    triggerColorRestoreZone: 'plaza',
    triggerQuestProgress: 'quest_start',
    nextId: 'kiki_reward',
  },
  kiki_after_grounding: {
    id: 'kiki_after_grounding',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Wah... melihat warna rumput, merasakan hembusan angin sejuk, dan mendengar suara gemericik air mancur benar-benar membuat kepalaku kembali tenang! Terima kasih teknik grounding-nya, Ezzel!',
    emotionAura: 'tenang',
    triggerColorRestoreZone: 'plaza',
    triggerQuestProgress: 'quest_start',
    nextId: 'kiki_reward',
  },
  kiki_after_stop: {
    id: 'kiki_after_stop',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Luar biasa! Dengan berhenti sejenak dan mengamati rasa takutku tanpa menghakimi diri sendiri, aku sadar masalah ini bisa kita selesaikan bersama! Terima kasih metode S.T.O.P-nya, Ezzel!',
    emotionAura: 'tenang',
    triggerColorRestoreZone: 'plaza',
    triggerQuestProgress: 'quest_start',
    nextId: 'kiki_reward',
  },
  kiki_after_shakeout: {
    id: 'kiki_after_shakeout',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Asyik! Tubuhku terasa sangat ringan setelah kita goyang-goyangkan tangan, kaki, dan ekor! Otot leherku tidak kaku lagi dan rasa panikku hilang! Terima kasih, Ezzel!',
    emotionAura: 'tenang',
    triggerColorRestoreZone: 'plaza',
    triggerQuestProgress: 'quest_start',
    nextId: 'kiki_reward',
  },
  kiki_reward: {
    id: 'kiki_reward',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Lihat, Ezzel! Air mancur plaza kembali memancarkan air jernih dan warna rumput di sekitar kita kembali hijau bersinar! Ini "Surat Wasiat Kuno" yang kutemukan, sepertinya penting untuk Kakek Ranu di Jembatan!',
    givesItem: 'item_letter',
  },

  // --- KAKEK RANU & JEMBATAN (BRANCHING IMPACTFUL CHOICE) ---
  ranu_intro: {
    id: 'ranu_intro',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'GRRR! Mau apa kalian bocah-bocah berisik?! Jembatan ini KUTUTUP! Pulang sana! Kalian cuma tahu main-main dan bikin rusak desa!',
    thoughtBubble: 'Semua orang hanya datang padaku saat ada yang rusak... Begitu tua dan lamban, aku ditinggalkan sendirian...',
    emotionAura: 'marah',
    choices: [
      {
        id: 'ranu_c1',
        text: 'Pilihan A: Validasi Rasa Sepi (Kakek pasti lelah bekerja sendiri... Kami sangat menghargai jasa Kakek).',
        impactScore: 20,
        resultDialogueId: 'ranu_path_empathy',
        branchTag: 'empathy_first',
      },
      {
        id: 'ranu_c2',
        text: 'Pilihan B: Solusi Logis & Jujur (Kakek, Bimo kehilangan roda gigi jam desa. Tolong buka jembatan agar kami bisa selesaikan bersama).',
        impactScore: 15,
        resultDialogueId: 'ranu_path_logic',
        branchTag: 'logic_first',
      },
      {
        id: 'ranu_c3',
        text: 'Kakek jahat! Jangan galak-galak begitu dong, nanti cepat tua!',
        impactScore: -10,
        resultDialogueId: 'ranu_angry_rebuke',
      },
    ],
  },
  ranu_angry_rebuke: {
    id: 'ranu_angry_rebuke',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'KAU BILANG APA?! Tidak punya sopan santun! Pergi dari jembatanku sebelum kuhalau dengan gagang sapu!',
    nextId: 'ranu_intro',
  },
  ranu_path_empathy: {
    id: 'ranu_path_empathy',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'A... apa katamu tadi, Nak Ezzel? Kalian... menghargaiku? (Kakek Ranu mengusap sudut matanya). Sudah bertahun-tahun tidak ada yang menanyakan kabarku selain meminta jembatan dibetulkan...',
    nextId: 'ranu_path_empathy_2',
  },
  ranu_path_empathy_2: {
    id: 'ranu_path_empathy_2',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'Maafkan Kakek yang membentak tadi. Rasa marah ini sebenarnya karena Kakek merasa kesepian dan takut tidak berguna lagi. Nih, jembatan kubuka lebar-lebar!',
    triggerColorRestoreZone: 'bridge',
    triggerQuestProgress: 'quest_bridge',
    givesItem: 'item_secret_key',
    nextId: 'ranu_path_empathy_3',
  },
  ranu_path_empathy_3: {
    id: 'ranu_path_empathy_3',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'Sebagai tanda terima kasih karena telah mendengar hatiku, bawalah "Kunci Kuno Gudang Arsip" ini. Dan satu rahasia: Pohon Suci di Hutan Utara menyukai doa ketulusan!',
  },

  ranu_path_logic: {
    id: 'ranu_path_logic',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'Hmm... Jadi si kecil Bimo sedang kebingungan mencari roda gigi jam? Anak itu memang berbakat, tapi sering terlalu keras pada dirinya sendiri...',
    nextId: 'ranu_path_logic_2',
  },
  ranu_path_logic_2: {
    id: 'ranu_path_logic_2',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'Baiklah! Jembatan kubuka. Tapi berjanjilah, sampaikan pada Bimo bahwa berbuat salah itu manusiawi, yang terpenting adalah berani belajar memperbaikinya!',
    triggerColorRestoreZone: 'bridge',
    triggerQuestProgress: 'quest_bridge',
    givesItem: 'item_bridge_pass',
  },

  // --- BIMO DI HUTAN SUNYI ---
  bimo_intro: {
    id: 'bimo_intro',
    speaker: 'Bimo',
    speakerRole: 'Murid Kelas 4',
    portrait: 'boy_glasses',
    text: '(Sesenggukan di balik pohon)... Huwaaa! Ezzel, aku ceroboh sekali! Roda gigi jam desa jatuh ke semak-semak dan sekarang jamnya mati. Aku pantas dijauhi semua orang...',
    thoughtBubble: 'Pasti semua teman menertawakanku... aku merasa sangat malu dan tak berharga...',
    emotionAura: 'sedih',
    choices: [
      {
        id: 'bimo_c1',
        text: 'Bimo, satu kesalahan tidak membuatmu jadi anak yang buruk. Kita cari solusinya bersama!',
        impactScore: 20,
        resultDialogueId: 'bimo_growth_mindset',
      },
      {
        id: 'bimo_c2',
        text: 'Tenang saja, Kakek Ranu sudah memaafkanmu dan justru memujimu berbakat!',
        impactScore: 15,
        resultDialogueId: 'bimo_ranu_praise',
      },
      {
        id: 'bimo_c3',
        text: 'Kamu sih kurang hati-hati! Makanya kalau pegang barang penting jangan melamun!',
        impactScore: -10,
        resultDialogueId: 'bimo_shame',
      },
    ],
  },
  bimo_shame: {
    id: 'bimo_shame',
    speaker: 'Bimo',
    speakerRole: 'Murid Kelas 4',
    portrait: 'boy_glasses',
    text: 'Huwaaa! Benar kan kataku... aku memang selalu merusak segalanya!',
    nextId: 'bimo_intro',
  },
  bimo_ranu_praise: {
    id: 'bimo_ranu_praise',
    speaker: 'Bimo',
    speakerRole: 'Murid Kelas 4',
    portrait: 'boy_glasses',
    text: 'Be... benarkah? Kakek Ranu tidak marah padaku? Padahal tadi aku takut sekali sampai lututku lemas...',
    nextId: 'bimo_growth_mindset',
  },
  bimo_growth_mindset: {
    id: 'bimo_growth_mindset',
    speaker: 'Bimo',
    speakerRole: 'Murid Kelas 4',
    portrait: 'boy_glasses',
    text: 'Perkataanmu benar, Ezzel... Guru di kelas selalu mengingatkan tentang "Growth Mindset" (Pola Pikir Berkembang): Kesalahan adalah bukti bahwa kita sedang berusaha!',
    nextId: 'bimo_growth_mindset_2',
  },
  bimo_growth_mindset_2: {
    id: 'bimo_growth_mindset_2',
    speaker: 'Bimo',
    speakerRole: 'Murid Kelas 4',
    portrait: 'boy_glasses',
    text: 'Ini dia, Ezzel! Aku berhasil menyelamatkan "Roda Gigi Emas Pusaka"! Bawalah ke Menara Jam di timur laut. Mari kembalikan dentang waktu dan warna desa kita!',
    triggerColorRestoreZone: 'forest',
    triggerQuestProgress: 'quest_bimo',
    givesItem: 'item_gold_gear',
  },

  // --- PROFESOR KOTEK (RAHASIA & MOMEN LUCU) ---
  kotek_intro: {
    id: 'kotek_intro',
    speaker: 'Profesor Kotek',
    speakerRole: 'Ayam Saintis Emosi',
    portrait: 'chicken_glasses',
    text: 'KUKU-RUYUK! Kroscek data kardiak! Selamat datang di pos pengamatan ayam tercerdas se-Lembah Nada Rasa!',
    thoughtBubble: 'Kacamata bulatku keren kan? Jangan sampai tahu kalau aku suka mematok cacing!',
    emotionAura: 'gembira',
    choices: [
      {
        id: 'kotek_c1',
        text: 'Halo Profesor! Apa yang sedang kamu teliti di sini?',
        impactScore: 10,
        resultDialogueId: 'kotek_fact',
      },
      {
        id: 'kotek_c2',
        text: 'Wah, ayam pakai kacamata?! Lucu sekali!',
        impactScore: 10,
        resultDialogueId: 'kotek_funny',
      },
    ],
  },
  kotek_funny: {
    id: 'kotek_funny',
    speaker: 'Profesor Kotek',
    speakerRole: 'Ayam Saintis Emosi',
    portrait: 'chicken_glasses',
    text: 'Eits, jangan salah! Kacamata ini berlensa fokus empati! Nah, karena kamu tersenyum melihatku, kamu baru saja melepaskan hormon Oksitosin dan Endorfin yang membuat tubuh rileks!',
    nextId: 'kotek_fact',
  },
  kotek_fact: {
    id: 'kotek_fact',
    speaker: 'Profesor Kotek',
    speakerRole: 'Ayam Saintis Emosi',
    portrait: 'chicken_glasses',
    text: 'Fakta Sains PSE: Saat manusia merasa marah atau panik, Otak Amigdala menyala seperti alarm kebakaran. Satu pelukan atau tawa ramah bisa mematikan alarm itu seketika! Ambil "Lencana Telur Ceria" ini!',
    thoughtBubble: 'Tawa dan humor sehat adalah pertahanan terbaik melawan hormon stres kortisol!',
    emotionAura: 'gembira',
    givesItem: 'item_egg_badge',
    unlocksBadge: 'badge_laughter_medicine',
    nextId: 'kotek_reward',
  },
  kotek_reward: {
    id: 'kotek_reward',
    speaker: 'Profesor Kotek',
    speakerRole: 'Ayam Saintis Emosi',
    portrait: 'chicken_glasses',
    text: 'KUKU-RUYUK! Selamat! Kamu berhasil memahami rahasia sains emosi dan resmi dianugerahi lencana kehormatan "Doktor Humor & Endorfin"! Ingat, senyuman tulus adalah obat penenang amigdala terbaik!',
    thoughtBubble: 'Sensor keceriaanku mendeteksi lonjakan hormon kebahagiaan 100% di seluruh desa!',
    emotionAura: 'gembira',
    unlocksBadge: 'badge_laughter_medicine',
  },

  // --- POHON RAHASIA (SECRET TREE) ---
  secret_tree: {
    id: 'secret_tree',
    speaker: 'Pohon Sahabat Purba',
    speakerRole: 'Rahasia Tersembunyi Hutan',
    portrait: 'tree',
    text: 'Dedaunan pohon purba ini berdesir lembut... Di celah akarnya yang dilapisi lumut keemasan, tersimpan sebuah Kapsul Waktu Tahun 1950.',
    choices: [
      {
        id: 'st_open',
        text: 'Buka Kapsul Waktu dengan niat persahabatan',
        impactScore: 15,
        resultDialogueId: 'secret_tree_capsule',
      },
    ],
  },
  secret_tree_capsule: {
    id: 'secret_tree_capsule',
    speaker: 'Pesan Kapsul Waktu 1950',
    speakerRole: 'Surat Pendiri Desa',
    portrait: 'scroll',
    text: '"Wahai anak masa depan: Bila kabut kesalahpahaman menutupi desamu, ingatlah tiga kata ajaib: Tolong, Maaf, dan Terima Kasih. Mendengarkan adalah hadiah terbesar bagi sesama manusia."',
    givesItem: 'item_friendship_capsule',
    unlocksBadge: 'badge_sacred_tree',
  },

  // --- CLIMAX AT THE CLOCK TOWER (PLOT TWIST: NENEK WILIS) ---
  tower_intro: {
    id: 'tower_intro',
    speaker: 'Sosok Misterius Kabut',
    speakerRole: 'Bayangan Menara',
    portrait: 'spirit_elder',
    text: 'Berhenti di sana... Mengapa kalian repot-repot memulihkan warna desa ini? Bukankah manusia hanya peduli pada kesibukannya masing-masing?',
    thoughtBubble: 'Aku lelah... bertahun-tahun di perpustakaan, melihat warga semakin sering berteriak dan saling menyakiti tanpa mau mendengar...',
    emotionAura: 'kecewa',
    choices: [
      {
        id: 'tw_c1',
        text: 'Siapa kamu sebenarnya? Apakah kamu monster pembuat kabut abu-abu?',
        impactScore: 5,
        resultDialogueId: 'tower_reveal',
      },
      {
        id: 'tw_c2',
        text: 'Kami datang bukan untuk bertengkar. Kompas kami merasakan rasa sedih yang sangat dalam di hatimu.',
        impactScore: 25,
        resultDialogueId: 'tower_empathy_twist',
      },
    ],
  },
  tower_reveal: {
    id: 'tower_reveal',
    speaker: 'Sosok Misterius Kabut',
    speakerRole: 'Bayangan Menara',
    portrait: 'spirit_elder',
    text: 'Monster? Haha... lihatlah lebih dekat dengan Kompas Hati kalian!',
    nextId: 'tower_empathy_twist',
  },
  tower_empathy_twist: {
    id: 'tower_empathy_twist',
    speaker: 'Nenek Wilis',
    speakerRole: 'Pustakawan Sepuh Desa',
    portrait: 'grandmother',
    text: '(Kabut menipis memperlihatkan seorang nenek tua berpakaian ramah dengan selendang batik). Namaku Wilis. Aku bukan monster. Kabut abu-abu ini adalah wujud nyata dari kata-kata pedas dan prasangka yang menumpuk di desa kita...',
    nextId: 'tower_twist_explanation',
  },
  tower_twist_explanation: {
    id: 'tower_twist_explanation',
    speaker: 'Nenek Wilis',
    speakerRole: 'Pustakawan Sepuh Desa',
    portrait: 'grandmother',
    text: 'Ketika orang-orang berhenti bertanya "Apa yang sedang kamu rasakan?", kristal jam waktu membeku. Tapi... kalian berhasil mendengarkan Kiki, memahami luka Kakek Ranu, dan mendampingi Bimo!',
    nextId: 'tower_final_choice',
  },
  tower_final_choice: {
    id: 'tower_final_choice',
    speaker: 'Nenek Wilis',
    speakerRole: 'Pustakawan Sepuh Desa',
    portrait: 'grandmother',
    text: 'Kini Roda Gigi Emas ada di tanganmu, Ezzel. Pilihan terakhir ada padamu: Pesan apa yang ingin kau canangkan saat lonceng harmoni berdentang?',
    choices: [
      {
        id: 'choice_ending_perfect',
        text: '"Pesan Empati": Mari kita deklarasikan Desa Pendengar Hati, di mana setiap perasaan diakui dan dihargai!',
        impactScore: 30,
        resultDialogueId: 'ending_perfect_scene',
      },
      {
        id: 'choice_ending_resilient',
        text: '"Pesan Keberanian": Mengakui kesalahan dan memaafkan adalah kekuatan sejati anak-anak Lembah!',
        impactScore: 25,
        resultDialogueId: 'ending_resilient_scene',
      },
    ],
  },
  ending_perfect_scene: {
    id: 'ending_perfect_scene',
    speaker: 'Lonceng Menara Jam',
    speakerRole: 'Harmoni Lembah',
    portrait: 'bell_tower',
    text: 'DIIING... DOOONG! Dentang lonceng menara menggetarkan seluruh lembah! Gelombang cahaya emas pelangi menyapu setiap sudut tanah, memulihkan seluruh warna dunia 100%!',
    triggerColorRestoreZone: 'tower',
    triggerQuestProgress: 'quest_tower',
    nextId: 'nenek_wilis_closing_perfect',
  },
  nenek_wilis_closing_perfect: {
    id: 'nenek_wilis_closing_perfect',
    speaker: 'Nenek Wilis',
    speakerRole: 'Pustakawan Sepuh Desa',
    portrait: 'grandmother',
    text: 'Air mata haru menetes di pipiku, Ezzel... Lihatlah sekeliling kita! Kabut prasangka abu-abu telah sirna selamanya. Bunga-bunga empati bermekaran harum di setiap sudut desa berkat ketulusan hatimu mendengarkan sesama.',
    thoughtBubble: 'Hatiku sangat damai melihat anak-anak kini tumbuh saling mengasihi dan mendengarkan.',
    nextId: 'ending_summary_perfect',
  },
  ending_resilient_scene: {
    id: 'ending_resilient_scene',
    speaker: 'Lonceng Menara Jam',
    speakerRole: 'Harmoni Lembah',
    portrait: 'bell_tower',
    text: 'DIIING... DOOONG! Suara dentang hangat menembus kabut! Pohon-pohon bersemi bunga warna-warni, burung berkicau, dan warga keluar rumah sambil tersenyum saling merangkul!',
    triggerColorRestoreZone: 'tower',
    triggerQuestProgress: 'quest_tower',
    nextId: 'nenek_wilis_closing_resilient',
  },
  nenek_wilis_closing_resilient: {
    id: 'nenek_wilis_closing_resilient',
    speaker: 'Nenek Wilis',
    speakerRole: 'Pustakawan Sepuh Desa',
    portrait: 'grandmother',
    text: 'Terima kasih dari lubuk hati terdalam, Ezzel... Kamu telah membuktikan bahwa keberanian untuk mengakui kesalahan dan saling memaafkan adalah kunci sejati kerukunan warga desa.',
    thoughtBubble: 'Keberanian anak ini telah meluluhkan prasangka dan menyatukan kembali hati warga.',
    nextId: 'ending_summary_resilient',
  },
  ending_summary_perfect: {
    id: 'ending_summary_perfect',
    speaker: 'Nenek Wilis & Seluruh Warga',
    speakerRole: 'Pesta Harmoni Lembah',
    portrait: 'celebration',
    text: 'Selamat, Ezzel! Seluruh warga bertepuk tangan riuh menyambut pahlawan cilik kita. Harmoni Lembah telah pulih 100% dan kamu resmi dianugerahi penghargaan tertinggi: "DUTA EMPATI EMAS KELAS 4 SD"!',
  },
  ending_summary_resilient: {
    id: 'ending_summary_resilient',
    speaker: 'Nenek Wilis & Seluruh Warga',
    speakerRole: 'Pesta Harmoni Lembah',
    portrait: 'celebration',
    text: 'Luar biasa, Ezzel! Harmoni Lembah telah pulih 100% dari kabut prasangka. Semua warga belajar bahwa mendengar dan memaafkan adalah kunci kedamaian. Kamu dianugerahi penghargaan: "PENJELAJAH HATI TANGGUH"!',
  },

  // --- KAK CITRA (4 ZONA REGULASI EMOSI) ---
  citra_intro: {
    id: 'citra_intro',
    speaker: 'Kak Citra',
    speakerRole: 'Konselor Cilik Lembah',
    portrait: 'girl_counselor',
    text: 'Halo Ezzel! Kamu sedang menjelajahi desa ya? Lihatlah bunga-bunga ini. Seperti bunga yang mekar aneka rupa, perasaan kita juga memiliki "4 Zona Warna" yang semuanya berharga!',
    choices: [
      {
        id: 'citra_c1',
        text: 'Apa saja 4 Zona Warna Emosi itu, Kak Citra?',
        impactScore: 10,
        resultDialogueId: 'citra_zones_explain',
      },
      {
        id: 'citra_c2',
        text: 'Bolehkah kalau aku sedang berada di Zona Merah (marah sekali)?',
        impactScore: 10,
        resultDialogueId: 'citra_zones_red_ask',
      },
    ],
  },
  citra_zones_explain: {
    id: 'citra_zones_explain',
    speaker: 'Kak Citra',
    speakerRole: 'Konselor Cilik Lembah',
    portrait: 'girl_counselor',
    text: '🌱 Hijau: Tenang, Fokus, Ceria (Siap Belajar). ⚡ Kuning: Cemas, Gelisah, Gembira Meluap. 🔥 Merah: Marah Besar, Panik, Ingin Meledak. 🌧️ Biru: Sedih, Lelah, Kecewa.',
    nextId: 'citra_zones_question',
  },
  citra_zones_red_ask: {
    id: 'citra_zones_red_ask',
    speaker: 'Kak Citra',
    speakerRole: 'Konselor Cilik Lembah',
    portrait: 'girl_counselor',
    text: 'Tentu saja boleh! TIDAK ADA emosi yang salah atau terlarang. Yang penting bukan menahan emosi, tapi bagaimana cara kita merespon agar aman dan tidak menyakiti diri maupun teman.',
    nextId: 'citra_zones_question',
  },
  citra_zones_question: {
    id: 'citra_zones_question',
    speaker: 'Kak Citra',
    speakerRole: 'Konselor Cilik Lembah',
    portrait: 'girl_counselor',
    text: 'Kuis Singkat PSE: Jika sahabatmu sedang di Zona Merah (marah berteriak), apa tindakan terbaikmu sebagai pendengar bijak?',
    choices: [
      {
        id: 'c_z1',
        text: 'Balas berteriak lebih keras agar dia diam.',
        impactScore: 0,
        resultDialogueId: 'citra_quiz_wrong',
      },
      {
        id: 'c_z2',
        text: 'Beri ruang aman, tenangkan diri sendiri dulu, lalu dengarkan saat dia sudah siap bernapas lega.',
        impactScore: 20,
        unlocksBadge: 'badge_counselor_zones',
        resultDialogueId: 'citra_reward',
      },
    ],
  },
  citra_quiz_wrong: {
    id: 'citra_quiz_wrong',
    speaker: 'Kak Citra',
    speakerRole: 'Konselor Cilik Lembah',
    portrait: 'girl_counselor',
    text: 'Aduh, jika api disiram minyak, kobaran api akan makin membesar! Saat teman di Zona Merah, amigdalanya sedang siaga. Lebih baik hadir tenang dan beri ruang aman.',
    nextId: 'citra_zones_question',
  },
  citra_reward: {
    id: 'citra_reward',
    speaker: 'Kak Citra',
    speakerRole: 'Konselor Cilik Lembah',
    portrait: 'girl_counselor',
    text: 'Tepat sekali, Ezzel! Luar biasa! Kamu telah menguasai Kesadaran Diri (Self-Awareness) tentang 4 Zona Regulasi. Terimalah lencana penghargaan ini di Buku Catatanmu!',
    unlocksBadge: 'badge_counselor_zones',
  },

  // --- KAKEK DAMAI (LINGKARAN KENDALI / CIRCLE OF CONTROL) ---
  damai_intro: {
    id: 'damai_intro',
    speaker: 'Kakek Damai',
    speakerRole: 'Praktisi Mindful & Bonsai',
    portrait: 'zen_master',
    text: 'Salam damai, anak muda Ezzel. Lihatlah air sungai yang mengalir ini... batu tak pernah memarahi air, dan air tak memaksa batu bergeser. Pernahkah kamu mendengar tentang "Lingkaran Kendali"?',
    choices: [
      {
        id: 'damai_c1',
        text: 'Apa itu Lingkaran Kendali, Kakek?',
        impactScore: 10,
        resultDialogueId: 'damai_control_explain',
      },
      {
        id: 'damai_c2',
        text: 'Bagaimana cara berhenti cemas tentang hal di luar kendali kita?',
        impactScore: 10,
        resultDialogueId: 'damai_control_tips',
      },
    ],
  },
  damai_control_explain: {
    id: 'damai_control_explain',
    speaker: 'Kakek Damai',
    speakerRole: 'Praktisi Mindful & Bonsai',
    portrait: 'zen_master',
    text: 'Ada hal di DALAM KENDALI kita: kata-kata kita, usaha belajar, cara merespon, dan niat minta maaf. Ada juga di LUAR KENDALI: cuaca hujan, perlakuan orang lain, atau masa lalu yang sudah terjadi.',
    nextId: 'damai_practice',
  },
  damai_control_tips: {
    id: 'damai_control_tips',
    speaker: 'Kakek Damai',
    speakerRole: 'Praktisi Mindful & Bonsai',
    portrait: 'zen_master',
    text: 'Saat cemas melanda, tanyakan pada hati nurani: "Apakah ini bisa kuubah dengan tindakanku sekarang?" Jika tidak, tarik napas dan lepaskan ke tangan semesta.',
    nextId: 'damai_practice',
  },
  damai_practice: {
    id: 'damai_practice',
    speaker: 'Kakek Damai',
    speakerRole: 'Praktisi Mindful & Bonsai',
    portrait: 'zen_master',
    text: 'Saat kamu kalah dalam permainan atau tugas kelompokmu ada yang belum selesai karena teman sakit, di mana energimu seharusnya kamu curahkan?',
    choices: [
      {
        id: 'd_p1',
        text: 'Terus mengeluh dan menyalahkan cuaca atau nasib buruk.',
        impactScore: 0,
        resultDialogueId: 'damai_wrong',
      },
      {
        id: 'd_p2',
        text: 'Fokus pada apa yang bisa kulakukan sekarang: membantu merapikan bagian yang ada dan belajar dari prosesnya.',
        impactScore: 20,
        unlocksBadge: 'badge_circle_of_control',
        resultDialogueId: 'damai_reward',
      },
    ],
  },
  damai_wrong: {
    id: 'damai_wrong',
    speaker: 'Kakek Damai',
    speakerRole: 'Praktisi Mindful & Bonsai',
    portrait: 'zen_master',
    text: 'Mengeluh menghabiskan energi untuk hal yang tak bisa diubah. Balikkan pandanganmu ke dalam kendali dirimu sendiri.',
    nextId: 'damai_practice',
  },
  damai_reward: {
    id: 'damai_reward',
    speaker: 'Kakek Damai',
    speakerRole: 'Praktisi Mindful & Bonsai',
    portrait: 'zen_master',
    text: 'Hati yang lapang! Kamu kini mengerti rahasia ketenangan batin. Bawalah lencana "Penguasa Lingkaran Kendali" sebagai tanda kearifanmu.',
    unlocksBadge: 'badge_circle_of_control',
  },

  // --- MOKA SI KUCING PUSTAKAWAN (MENDENGARKAN AKTIF) ---
  moka_intro: {
    id: 'moka_intro',
    speaker: 'Moka',
    speakerRole: 'Kucing Pustakawan Lembut',
    portrait: 'cat_librarian',
    text: 'Purrr... Meow! Duduklah di sampingku sejenak di bangku kayu ini, Ezzel. Kadang kita begitu sibuk menyiapkan jawaban di kepala saat orang lain berbicara, sampai lupa MENDENGAR sungguhan.',
    choices: [
      {
        id: 'moka_c1',
        text: 'Bagaimana cara mendengarkan dengan mata hati, Moka?',
        impactScore: 10,
        resultDialogueId: 'moka_listen_explain',
      },
      {
        id: 'moka_c2',
        text: 'Kenapa orang sering merasa sakit hati saat ceritanya langsung dipotong?',
        impactScore: 10,
        resultDialogueId: 'moka_cut_explain',
      },
    ],
  },
  moka_listen_explain: {
    id: 'moka_listen_explain',
    speaker: 'Moka',
    speakerRole: 'Kucing Pustakawan Lembut',
    portrait: 'cat_librarian',
    text: '3 Kunci Mendengar Aktif: 1) Letakkan gawai & tatap mata teman. 2) Tahan keinginan memotong atau menggurui. 3) Berikan respon validasi: "Pasti sedih ya rasanya jika ada di posisimu."',
    nextId: 'moka_question',
  },
  moka_cut_explain: {
    id: 'moka_cut_explain',
    speaker: 'Moka',
    speakerRole: 'Kucing Pustakawan Lembut',
    portrait: 'cat_librarian',
    text: 'Ketika cerita kita dipotong dengan "Ah gitu doang, aku dulu lebih parah!", kita merasa perasaan kita dianggap remeh dan tidak berharga.',
    nextId: 'moka_question',
  },
  moka_question: {
    id: 'moka_question',
    speaker: 'Moka',
    speakerRole: 'Kucing Pustakawan Lembut',
    portrait: 'cat_librarian',
    text: 'Saat ada teman menceritakan bahwa ia baru saja kehilangan pensil kesayangannya, respon mana yang menunjukkan empati sejati?',
    choices: [
      {
        id: 'm_q1',
        text: '"Makanya jangan teledor! Beli lagi kan gampang."',
        impactScore: 0,
        resultDialogueId: 'moka_wrong',
      },
      {
        id: 'm_q2',
        text: '"Pasti sedih ya, pensil itu kan punya kenangan khusus. Mau kubantu cari di kolong meja bersama?"',
        impactScore: 20,
        unlocksBadge: 'badge_active_listening',
        resultDialogueId: 'moka_reward',
      },
    ],
  },
  moka_wrong: {
    id: 'moka_wrong',
    speaker: 'Moka',
    speakerRole: 'Kucing Pustakawan Lembut',
    portrait: 'cat_librarian',
    text: 'Meow... ucapan menghakimi membuat teman menutup cangkang perasaannya. Cobalah dengan validasi empati.',
    nextId: 'moka_question',
  },
  moka_reward: {
    id: 'moka_reward',
    speaker: 'Moka',
    speakerRole: 'Kucing Pustakawan Lembut',
    portrait: 'cat_librarian',
    text: 'Purrr! Kehangatanmu terasa menyejukkan hati. Kamu pantas menerima lencana "Sahabat Pendengar Sejati"! Jadilah teladan pendengar yang baik untuk teman-temanmu ya!',
    unlocksBadge: 'badge_active_listening',
  },

  // --- WORLD INSPECTION / EXAMINE OBJECTS ---
  fountain_examine: {
    id: 'fountain_examine',
    speaker: 'Air Mancur Harmoni',
    speakerRole: 'Jantung Alun-Alun',
    portrait: 'fountain',
    text: 'Gemericik air mancur memantulkan sinar matahari pagi dengan riak tenang. Air mengingatkan kita bahwa emosi seperti riak permukaan: bila didiamkan sejenak, dasar dan kejernihan akan kembali terlihat.',
  },
  signpost_examine: {
    id: 'signpost_examine',
    speaker: 'Plang Petunjuk Arah',
    speakerRole: 'Persimpangan Desa',
    portrait: 'signpost',
    text: '📍 Plang Kayu Berukir: [⬅️ Barat: Rumah Penduduk & Pos Kiki] [⬆️ Utara: Hutan Sunyi & Pohon Purba] [➡️ Timur: Jembatan Kayu & Menara Jam Waktu] [⬇️ Selatan: Alun-Alun & Air Mancur Harmoni].',
  },
  signpost_forest: {
    id: 'signpost_forest',
    speaker: 'Plang Petunjuk Arah Hutan',
    speakerRole: 'Batas Hutan Pinus Asri',
    portrait: 'signpost',
    text: '📍 Plang Hutan Pinus Asri: [⬆️ Utara: Pondok Hutan Kayu Pak Teguh & Jalur Pinus] [↖️ Barat Laut: Pohon Keramat Rahasia] [⬇️ Selatan: Alun-Alun Lembah & Air Mancur Harmoni].',
  },
  forest_cabin_examine: {
    id: 'forest_cabin_examine',
    speaker: 'Pondok Hutan Pak Teguh',
    speakerRole: 'Kabin Kayu Cedar & Tempat Istirahat Penjaga Hutan',
    portrait: 'woodcutter',
    emotionAura: 'tenang',
    thoughtBubble: 'Hutan yang sehat bukan hutan yang tak pernah disentuh, melainkan hutan yang dirawat dengan cinta, kebijaksanaan, dan kesadaran.',
    text: '🌲 Pondok kabin log kayu cedar yang kokoh dan hangat. Di bawah naungan atap berselimut lumut hijau segar, cerobong batu kali mengepulkan aroma sedap pembakaran kayu pinus kering. Di serambi depan, lentera tembaga menyinari ukiran kapak bersilang lambang harmoni manusia dan rimba.',
    choices: [
      {
        id: 'c_cabin_philosophy',
        text: '🪵 Pelajari Filosofi Pemangkasan Ranting & Regulasi Diri',
        impactScore: 5,
        resultDialogueId: 'forest_cabin_philosophy',
      },
      {
        id: 'c_cabin_leave',
        text: '👋 Ucapkan terima kasih dan lanjutkan penjelajahan',
        impactScore: 2,
        resultDialogueId: 'forest_cabin_farewell',
      },
    ],
  },
  forest_cabin_farewell: {
    id: 'forest_cabin_farewell',
    speaker: 'Pondok Hutan Pak Teguh',
    speakerRole: 'Kabin Kayu Cedar & Tempat Istirahat Penjaga Hutan',
    portrait: 'woodcutter',
    emotionAura: 'tenang',
    text: '🌲 Udara segar semerbak pinus menyegarkan dadamu. Langkah kakimu terasa semakin ringan, siap melanjutkan petualangan memulihkan warna harmoni lembah.',
  },
  forest_cabin_philosophy: {
    id: 'forest_cabin_philosophy',
    speaker: 'Pak Teguh',
    speakerRole: 'Penebang Pohon Hutan Bijak',
    portrait: 'woodcutter',
    emotionAura: 'tenang',
    thoughtBubble: 'Memotong ranting lapuk memberi ruang bagi tunas baru bertumbuh mekar ke arah cahaya matahari.',
    text: '🌲 Pak Teguh tersenyum ramah: "Setiap batang kayu di tumpukan samping pondok ini berasal dari dahan kering yang sudah waktunya dipangkas. Sama seperti emosi kita—jika amarah atau dendam dibiarkan menumpuk, ia akan membebani jiwa. Belajarlah memotong siklus amarah dengan jeda napas, agar hati kita kembali lapang dan bercahaya!"',
  },
  signpost_farm: {
    id: 'signpost_farm',
    speaker: 'Plang Kawasan Pertanian',
    speakerRole: 'Kebun Harapan Desa',
    portrait: 'signpost',
    text: '📍 Plang Kawasan Pertanian & Perkebunan: [⬅️ Barat: Pondok Petani & Tumpukan Jerami] [⬇️ Selatan: Ladang Wortel, Kubis Segar, Gandum Emas & Sumur Air] [➡️ Timur: Alun-Alun & Perkebunan Apel/Jeruk].',
  },

  // --- MENARA JAM HARMONI (WORLD EXAMINE & ASPEK INFORMASI EDUKATIF) ---
  tower_examine: {
    id: 'tower_examine',
    speaker: 'Menara Jam Harmoni',
    speakerRole: 'Monumen Kuno Lembah (Abad ke-18)',
    portrait: 'clock_tower',
    emotionAura: 'tenang',
    thoughtBubble: 'Detak waktu bukan sekadar jarum yang berputar, melainkan denyut kebersamaan dan keterhubungan setiap jiwa di lembah ini.',
    text: '🏛️ Kamu berdiri di hadapan Menara Jam Harmoni yang menjulang setinggi 20 meter dengan arsitektur batu andesit berukir. Di puncaknya, jarum jam raksasa dan Lonceng Perunggu kuno tampak membeku, menanti pulihnya dialog hati antarwarga.',
    choices: [
      {
        id: 'c_tw_hist',
        text: '📜 Baca Prasasti Sejarah & Filosofi Menara',
        impactScore: 5,
        resultDialogueId: 'tower_examine_history',
      },
      {
        id: 'c_tw_mech',
        text: '⚙️ Periksa 4 Roda Gigi & Makna Pembelajaran (PSE)',
        impactScore: 5,
        resultDialogueId: 'tower_examine_mechanics',
      },
      {
        id: 'c_tw_bell',
        text: '🔔 Dengarkan Dentang Resonansi Lonceng Kuno',
        impactScore: 5,
        resultDialogueId: 'tower_examine_bell',
      },
      {
        id: 'c_tw_exit',
        text: '🚪 Selesai Memeriksa Menara (Lanjut Petualangan)',
        impactScore: 0,
        resultDialogueId: '',
      },
    ],
  },
  tower_examine_history: {
    id: 'tower_examine_history',
    speaker: 'Prasasti Batu Pendiri Menara',
    speakerRole: 'Catatan Sejarah Lembah (1785)',
    portrait: 'scroll',
    text: '📜 "Didirikan tahun 1785 oleh Ki Waskita dan para perintis lembah. Menara ini dirancang sebagai Barometer Harmoni Batin. Pendulum jam melambangkan Keseimbangan Emosi (Emotional Equilibrium): amarah dan kekecewaan bisa mengayunkan jiwa ke tepi, namun melalui jeda napas sadar, kita selalu bisa kembali ke titik pusat yang damai."',
    choices: [
      {
        id: 'c_twh_mech',
        text: '⚙️ Bagaimana cara kerja 4 Roda Gigi jam ini?',
        impactScore: 5,
        resultDialogueId: 'tower_examine_mechanics',
      },
      {
        id: 'c_twh_bell',
        text: '🔔 Ingin mendengarkan resonansi lonceng menara',
        impactScore: 5,
        resultDialogueId: 'tower_examine_bell',
      },
      {
        id: 'c_twh_back',
        text: '🔙 Kembali ke menu pengamatan menara',
        impactScore: 0,
        resultDialogueId: 'tower_examine',
      },
      {
        id: 'c_twh_exit',
        text: '🚪 Selesai Membaca & Lanjut Eksplorasi Desa',
        impactScore: 0,
        resultDialogueId: '',
      },
    ],
  },
  tower_examine_mechanics: {
    id: 'tower_examine_mechanics',
    speaker: 'Mekanisme Jam Harmoni',
    speakerRole: '4 Pilar Keselarasan Sosial Emosional (PSE)',
    portrait: 'clock_tower',
    text: '⚙️ Ruang mesin jam digerakkan oleh 4 Roda Gigi Utama:\n1. 🌟 Roda Alun-Alun: Kesadaran Diri (Mengenali emosi diri tanpa menghakimi).\n2. 🤝 Roda Jembatan: Empati & Menghargai (Memahami perasaan orang lain).\n3. 🌱 Roda Kebun & Hutan: Regulasi Emosi & Growth Mindset (Mengelola respon & belajar dari kesalahan).\n4. 🕊️ Roda Puncak Menara: Rekonsiliasi & Resolusi Konflik (Mendengarkan dengan hati terbuka).',
    choices: [
      {
        id: 'c_twm_hist',
        text: '📜 Baca prasasti sejarah menara',
        impactScore: 5,
        resultDialogueId: 'tower_examine_history',
      },
      {
        id: 'c_twm_bell',
        text: '🔔 Bunyikan lonceng untuk jeda sadar (Mindful Pause)',
        impactScore: 5,
        resultDialogueId: 'tower_examine_bell',
      },
      {
        id: 'c_twm_back',
        text: '🔙 Kembali ke menu pengamatan menara',
        impactScore: 0,
        resultDialogueId: 'tower_examine',
      },
      {
        id: 'c_twm_exit',
        text: '🚪 Selesai Memeriksa & Lanjut Petualangan',
        impactScore: 0,
        resultDialogueId: '',
      },
    ],
  },
  tower_examine_bell: {
    id: 'tower_examine_bell',
    speaker: 'Lonceng Harmoni Perunggu',
    speakerRole: 'Jeda Sadar (The Power of Pause)',
    portrait: 'clock_tower',
    emotionAura: 'tenang',
    text: '🔔 *DUNGGGG...* Gema merdu lonceng perunggu bergetar jernih menembus lembah. Ambil napas dalam 4 hitungan... tahan 2 hitungan... hembuskan perlahan 6 hitungan. Rasakan ketegangan menguap dan ketenangan menara meresap ke dalam dada.',
    choices: [
      {
        id: 'c_twb_again',
        text: '🔔 Dengarkan dentang lonceng sekali lagi',
        impactScore: 5,
        resultDialogueId: 'tower_examine_bell',
      },
      {
        id: 'c_twb_mech',
        text: '⚙️ Periksa roda gigi jam',
        impactScore: 5,
        resultDialogueId: 'tower_examine_mechanics',
      },
      {
        id: 'c_twb_back',
        text: '🔙 Kembali ke menu pengamatan menara',
        impactScore: 0,
        resultDialogueId: 'tower_examine',
      },
      {
        id: 'c_twb_exit',
        text: '🚪 Selesai & Lanjut Eksplorasi Desa',
        impactScore: 0,
        resultDialogueId: '',
      },
    ],
  },
  tower_examine_restored: {
    id: 'tower_examine_restored',
    speaker: 'Menara Jam Harmoni (Telah Pulih!)',
    speakerRole: 'Pusat Cahaya Keemasan Lembah',
    portrait: 'clock_tower',
    emotionAura: 'gembira',
    thoughtBubble: 'Seluruh roda gigi berputar anggun! Langit biru membentang cerah dan detak waktu mengalir dalam kedamaian.',
    text: '✨ Luar biasa! Menara Jam Harmoni kini memancarkan cahaya keemasan hangat dari dial kristalnya. Keempat roda gigi utama berputar selaras, panji-panji lembah berkibar gagah ditiup angin sepoi, dan kabut abu-abu telah sirna selamanya!',
    choices: [
      {
        id: 'c_twr_hist',
        text: '📜 Baca prasasti sejarah & filosofi menara',
        impactScore: 5,
        resultDialogueId: 'tower_examine_history',
      },
      {
        id: 'c_twr_mech',
        text: '⚙️ Pelajari 4 pilar roda gigi PSE',
        impactScore: 5,
        resultDialogueId: 'tower_examine_mechanics',
      },
      {
        id: 'c_twr_bell',
        text: '🔔 Dentangkan Lonceng Harmoni Perayaan',
        impactScore: 10,
        resultDialogueId: 'tower_examine_bell',
      },
      {
        id: 'c_twr_exit',
        text: '🚪 Selesai Menikmati & Lanjut Petualangan',
        impactScore: 0,
        resultDialogueId: '',
      },
    ],
  },

  // --- PAK JOKO (PETANI KEBUN HARAPAN - GROWTH MINDSET) ---
  joko_intro: {
    id: 'joko_intro',
    speaker: 'Pak Joko',
    speakerRole: 'Petani Kebun Harapan',
    portrait: 'farmer',
    text: 'Halo nak! Segar sekali udara pagi ini, ya? Lihatlah barisan wortel, kubis, dan gandum emas yang sedang kusiram ini. Semuanya berawal dari benih mungil yang terkubur di dalam tanah gelap.',
    thoughtBubble: 'Tanaman tak bisa dipaksa ditarik agar lekas tinggi. Butuh waktu, air, dan kesabaran untuk bertumbuh.',
    emotionAura: 'tenang',
    nextId: 'joko_lesson',
  },
  joko_lesson: {
    id: 'joko_lesson',
    speaker: 'Pak Joko',
    speakerRole: 'Petani Kebun Harapan',
    portrait: 'farmer',
    text: 'Dalam ilmu Sosial Emosional (PSE), ada konsep bernama "Pola Pikir Berkembang" (Growth Mindset). Sama seperti tunas tanaman, otak dan kemampuan kita bisa terus bertumbuh lewat latihan dan pantang menyerah.',
    choices: [
      {
        id: 'c_joko_ask',
        text: 'Bagaimana bila kita melakukan kesalahan saat belajar, Pak Joko?',
        impactScore: 10,
        resultDialogueId: 'joko_question',
      },
      {
        id: 'c_joko_pass',
        text: 'Wah, hasil panennya subur sekali Pak Joko!',
        impactScore: 5,
        resultDialogueId: 'joko_compliment',
      },
    ],
  },
  joko_compliment: {
    id: 'joko_compliment',
    speaker: 'Pak Joko',
    speakerRole: 'Petani Kebun Harapan',
    portrait: 'farmer',
    text: 'Terima kasih, nak! Tapi kesuburan ini datang dari kegagalan panen bertahun-tahun yang lalu. Dulu tanamanku sering layu karena salah takaran air, tapi Pak Joko belajar dari setiap kekeliruan.',
    nextId: 'joko_question',
  },
  joko_question: {
    id: 'joko_question',
    speaker: 'Pak Joko',
    speakerRole: 'Petani Kebun Harapan',
    portrait: 'farmer',
    text: 'Nah, coba jawab pertanyaan petani tua ini: Ketika kamu mendapat nilai ulangan yang belum memuaskan atau belum bisa memecahkan soal matematika yang sulit, sikap mana yang mencerminkan Growth Mindset?',
    choices: [
      {
        id: 'c_joko_fixed',
        text: '"Memang aku tidak berbakat di bidang ini, menyerah saja."',
        impactScore: 0,
        resultDialogueId: 'joko_fixed_feedback',
      },
      {
        id: 'c_joko_growth',
        text: '"Aku belum bisa sekarang, tapi dengan cara belajar baru dan bertanya, kemampuanku pasti bertambah!"',
        impactScore: 20,
        unlocksBadge: 'badge_growth_mindset',
        resultDialogueId: 'joko_growth_reward',
      },
    ],
  },
  joko_fixed_feedback: {
    id: 'joko_fixed_feedback',
    speaker: 'Pak Joko',
    speakerRole: 'Petani Kebun Harapan',
    portrait: 'farmer',
    text: 'Waduh, itu namanya Pola Pikir Tetap (Fixed Mindset). Jangan batasi potensi dirimu, nak! Tambahkan kata "BELUM BISA" daripada "TIDAK BISA". Ayo coba renungkan lagi.',
    nextId: 'joko_question',
  },
  joko_growth_reward: {
    id: 'joko_growth_reward',
    speaker: 'Pak Joko',
    speakerRole: 'Petani Kebun Harapan',
    portrait: 'farmer',
    text: 'Tepat sekali! Kata sakti itu adalah "BELUM". Kesalahan adalah pupuk terbaik bagi kebijaksanaan. Terimalah lencana "Pakar Pola Pikir Berkembang" ini! Teruslah menyiram impianmu dengan ketekunan!',
    unlocksBadge: 'badge_growth_mindset',
  },

  // --- DIDI (PENGELANA CILIK DESA - RELATIONSHIP SKILLS & FRIENDLINESS) ---
  didi_intro: {
    id: 'didi_intro',
    speaker: 'Didi',
    speakerRole: 'Pengelana Cilik Desa',
    portrait: 'wandering_scout',
    text: 'Hai halo sahabat baru! *melambaikan tangan ceria* Namaku Didi! Aku suka sekali berjalan keliling desa, dari persimpangan alun-alun sampai ke kebun buah di timur!',
    thoughtBubble: 'Menyapa orang dengan senyuman selalu membuat hatiku hangat dan ceria!',
    emotionAura: 'gembira',
    nextId: 'didi_lesson',
  },
  didi_lesson: {
    id: 'didi_lesson',
    speaker: 'Didi',
    speakerRole: 'Pengelana Cilik Desa',
    portrait: 'wandering_scout',
    text: 'Tahukah kamu rahasia terbesarku saat bertualang? Keterampilan Membangun Relasi (Relationship Skills) dimulai dari hal yang sangat sederhana: senyuman tulus dan sapaan yang ramah!',
    choices: [
      {
        id: 'c_didi_q',
        text: 'Bagaimana kalau kita merasa malu atau canggung saat bertemu orang baru, Didi?',
        impactScore: 10,
        resultDialogueId: 'didi_question',
      },
      {
        id: 'c_didi_fun',
        text: 'Wah, tas ranselmu tampak penuh perlengkapan petualangan!',
        impactScore: 5,
        resultDialogueId: 'didi_backpack',
      },
    ],
  },
  didi_backpack: {
    id: 'didi_backpack',
    speaker: 'Didi',
    speakerRole: 'Pengelana Cilik Desa',
    portrait: 'wandering_scout',
    text: 'Hehehe! Di dalam tasku ada peta desa, kompas kecil, dan buku catatan teman-teman baru yang kujumpai sepanjang jalan!',
    nextId: 'didi_question',
  },
  didi_question: {
    id: 'didi_question',
    speaker: 'Didi',
    speakerRole: 'Pengelana Cilik Desa',
    portrait: 'wandering_scout',
    text: 'Rasa canggung itu wajar banget! Nah, jika ada anak baru yang tampak sendirian dan belum punya teman di halaman bermain, apa tindakan terbaik yang bisa kita ambil?',
    choices: [
      {
        id: 'c_didi_ignore',
        text: 'Diamkan saja, nanti juga dia cari teman sendiri kalau mau.',
        impactScore: 0,
        resultDialogueId: 'didi_wrong',
      },
      {
        id: 'c_didi_greet',
        text: 'Tersenyum ramah, menyapa namanya, dan mengajaknya ikut bermain bersama.',
        impactScore: 20,
        unlocksBadge: 'badge_friendly_greeter',
        resultDialogueId: 'didi_reward',
      },
    ],
  },
  didi_wrong: {
    id: 'didi_wrong',
    speaker: 'Didi',
    speakerRole: 'Pengelana Cilik Desa',
    portrait: 'wandering_scout',
    text: 'Wah, kalau didiamkan dia pasti merasa kesepian dan terasing. Ingat, satu sapaan kecil kita bisa menjadi pelita besar bagi harinya! Yuk coba lagi!',
    nextId: 'didi_question',
  },
  didi_reward: {
    id: 'didi_reward',
    speaker: 'Didi',
    speakerRole: 'Pengelana Cilik Desa',
    portrait: 'wandering_scout',
    text: 'Hebat sekali! Kebaikan dan sapaan hangat adalah bahasa universal yang bisa dimengerti setiap hati. Ini lencana "Duta Sapaan Ramah Desa" untukmu! Mari tebarkan senyuman ke mana pun kita pergi!',
    unlocksBadge: 'badge_friendly_greeter',
    nextId: 'didi_resolved',
  },
  didi_resolved: {
    id: 'didi_resolved',
    speaker: 'Didi',
    speakerRole: 'Pengelana Cilik Desa',
    portrait: 'wandering_scout',
    text: 'Halo kawan penjelajah! Desa terasa begitu ceria dan hangat. Teruslah menyapa setiap orang yang kau jumpai dengan senyuman tulus!',
    thoughtBubble: 'Melihat orang lain tersenyum membuat langkah kakiku semakin bersemangat!',
    emotionAura: 'gembira',
  },

  // --- PAK TEGUH (PENEBANG POHON HUTAN BIJAK - MANAJEMEN AMARAH) ---
  teguh_intro: {
    id: 'teguh_intro',
    speaker: 'Pak Teguh',
    speakerRole: 'Penebang Pohon Hutan Bijak',
    portrait: 'woodcutter',
    text: 'Tak... tak... tak! Salam anak muda! Sedang menjelajahi hutan pinus yang asri ini? Jangan khawatir, kapakku ini hanya memotong ranting pohon lapuk dan dahan berduri yang menghalangi jalan.',
    thoughtBubble: 'Hutan mengajarkan bahwa pohon yang kaku akan patah tertiup badai, tapi pohon yang fleksibel akan tetap kokoh berdiri.',
    emotionAura: 'tenang',
    choices: [
      {
        id: 'c_teguh_anger',
        text: 'Mengapa memotong ranting lapuk diibaratkan seperti mengelola amarah, Pak Teguh?',
        impactScore: 10,
        resultDialogueId: 'teguh_lesson',
      },
      {
        id: 'c_teguh_axe',
        text: 'Kapakmu terlihat sangat kokoh dan terawat, Pak Teguh!',
        impactScore: 5,
        resultDialogueId: 'teguh_axe_reply',
      },
    ],
  },
  teguh_axe_reply: {
    id: 'teguh_axe_reply',
    speaker: 'Pak Teguh',
    speakerRole: 'Penebang Pohon Hutan Bijak',
    portrait: 'woodcutter',
    text: 'Tentu! Kapak ini diasah dengan kesabaran. Sama seperti mengasah akal budi kita: bila tumpul oleh amarah mendidih, kita bisa melukai hal-hal indah di sekitar kita.',
    nextId: 'teguh_lesson',
  },
  teguh_lesson: {
    id: 'teguh_lesson',
    speaker: 'Pak Teguh',
    speakerRole: 'Penebang Pohon Hutan Bijak',
    portrait: 'woodcutter',
    text: 'Dalam ilmu Sosial Emosional (PSE), saat amarah menyala di dada seperti bara api, ada seni "Manajemen Diri" (Self-Management). Coba jawab kuis penebang tua ini:',
    nextId: 'teguh_question',
  },
  teguh_question: {
    id: 'teguh_question',
    speaker: 'Pak Teguh',
    speakerRole: 'Penebang Pohon Hutan Bijak',
    portrait: 'woodcutter',
    text: 'Ketika ada teman yang tidak sengaja merusak hasil karyamu dan kamu merasa sangat marah, tindakan apa yang mencerminkan pemotongan siklus amarah yang bijak?',
    choices: [
      {
        id: 'c_teguh_retaliate',
        text: 'Langsung membalas merusak barang milik teman tersebut agar dia tahu rasanya.',
        impactScore: 0,
        resultDialogueId: 'teguh_wrong',
      },
      {
        id: 'c_teguh_timeout',
        text: 'Mengambil jeda (time-out), menarik napas dalam untuk meredakan amigdala, lalu menyampaikan rasa kecewa dengan nada tenang (Pesan-Aku).',
        impactScore: 20,
        unlocksBadge: 'badge_woodcutter_anger',
        resultDialogueId: 'teguh_reward',
      },
    ],
  },
  teguh_wrong: {
    id: 'teguh_wrong',
    speaker: 'Pak Teguh',
    speakerRole: 'Penebang Pohon Hutan Bijak',
    portrait: 'woodcutter',
    text: 'Aduh! Jika api dibalas api, seluruh hutan persahabatan akan terbakar hangus! Ambil jeda napas sejenak, yuk coba pikirkan lagi.',
    nextId: 'teguh_question',
  },
  teguh_reward: {
    id: 'teguh_reward',
    speaker: 'Pak Teguh',
    speakerRole: 'Penebang Pohon Hutan Bijak',
    portrait: 'woodcutter',
    text: 'Tepat sekali! Luar biasa! Kamu tahu kapan harus meletakkan kapak amarah dan memilih kedamaian. Ini lencana "Penebang Amarah Bijak" untukmu!',
    unlocksBadge: 'badge_woodcutter_anger',
    nextId: 'teguh_resolved',
  },
  teguh_resolved: {
    id: 'teguh_resolved',
    speaker: 'Pak Teguh',
    speakerRole: 'Penebang Pohon Hutan Bijak',
    portrait: 'woodcutter',
    text: 'Hutan pinus ini semakin sejuk berkat ketenangan hatimu. Ingat, jeda napas 5 detik selalu lebih baik daripada penyesalan bertahun-tahun!',
    thoughtBubble: 'Jiwa yang tenang mampu menebang segala kebencian dengan kelembutan.',
    emotionAura: 'tenang',
  },

  // --- IBU SARI (PETANI KEBUN BUAH HUTAN - RASA SYUKUR & BERBAGI) ---
  sari_intro: {
    id: 'sari_intro',
    speaker: 'Ibu Sari',
    speakerRole: 'Petani Kebun Buah Hutan',
    portrait: 'fruit_farmer',
    text: 'Ahai, selamat pagi anak manis! Hirup wangi apel merah dan jeruk segar ini! Pohon-pohon buah hutan ini sedang berbuah lebat sekali tahun ini.',
    thoughtBubble: 'Buah yang paling manis rasanya adalah buah yang kita petik dan kita nikmati bersama sahabat.',
    emotionAura: 'gembira',
    choices: [
      {
        id: 'c_sari_gratitude',
        text: 'Bagaimana cara pohon-pohon ini bisa menghasilkan buah yang begitu ranum, Bu Sari?',
        impactScore: 10,
        resultDialogueId: 'sari_lesson',
      },
      {
        id: 'c_sari_taste',
        text: 'Wah, buah apelnya tampak sangat lezat dan segar sekali!',
        impactScore: 5,
        resultDialogueId: 'sari_taste_reply',
      },
    ],
  },
  sari_taste_reply: {
    id: 'sari_taste_reply',
    speaker: 'Ibu Sari',
    speakerRole: 'Petani Kebun Buah Hutan',
    portrait: 'fruit_farmer',
    text: 'Hihihi, tentu saja! Karena setiap pohon dirawat dengan rasa syukur dan kasih sayang setiap pagi.',
    nextId: 'sari_lesson',
  },
  sari_lesson: {
    id: 'sari_lesson',
    speaker: 'Ibu Sari',
    speakerRole: 'Petani Kebun Buah Hutan',
    portrait: 'fruit_farmer',
    text: 'Dalam pembelajaran emosi, ada buah yang disebut "Rasa Syukur" (Gratitude) dan "Kesadaran Sosial" (Social-Awareness). Coba jawab teka-teki manis dari Ibu Sari:',
    nextId: 'sari_question',
  },
  sari_question: {
    id: 'sari_question',
    speaker: 'Ibu Sari',
    speakerRole: 'Petani Kebun Buah Hutan',
    portrait: 'fruit_farmer',
    text: 'Ketika kamu berhasil meraih juara kelas atau memenangkan lomba, bagaimana cara terbaik melipatgandakan rasa syukurmu menurut nilai sosial emosional?',
    choices: [
      {
        id: 'c_sari_boast',
        text: 'Memamerkan piala terus-menerus dan mengejek teman yang belum berhasil agar merasa lebih hebat.',
        impactScore: 0,
        resultDialogueId: 'sari_wrong',
      },
      {
        id: 'c_sari_share',
        text: 'Mengucapkan terima kasih kepada guru dan orang tua, tetap rendah hati, serta menyemangati teman yang sedang berjuang.',
        impactScore: 20,
        unlocksBadge: 'badge_fruit_gratitude',
        resultDialogueId: 'sari_reward',
      },
    ],
  },
  sari_wrong: {
    id: 'sari_wrong',
    speaker: 'Ibu Sari',
    speakerRole: 'Petani Kebun Buah Hutan',
    portrait: 'fruit_farmer',
    text: 'Duh, menyombongkan diri membuat buah persahabatan membusuk dan teman menjauh. Rasa syukur yang sejati melahirkan kerendahan hati. Coba lagi ya!',
    nextId: 'sari_question',
  },
  sari_reward: {
    id: 'sari_reward',
    speaker: 'Ibu Sari',
    speakerRole: 'Petani Kebun Buah Hutan',
    portrait: 'fruit_farmer',
    text: 'Manis sekali budi pekertimu! Rasa syukur melahirkan kebahagiaan sejati yang tak pernah layu. Terimalah lencana "Pemetik Rasa Syukur & Berbagi" ini!',
    unlocksBadge: 'badge_fruit_gratitude',
    nextId: 'sari_resolved',
  },
  sari_resolved: {
    id: 'sari_resolved',
    speaker: 'Ibu Sari',
    speakerRole: 'Petani Kebun Buah Hutan',
    portrait: 'fruit_farmer',
    text: 'Melihat anak-anak berbudi pekerti luhur seperti kalian membuat buah di kebun terasa seribu kali lebih manis! Teruslah berbagi kebaikan ya!',
    thoughtBubble: 'Hati yang bersyukur adalah tanah tersubur bagi kebahagiaan hidup.',
    emotionAura: 'gembira',
  },

  // --- BUNG JALA (PEMANCING SABAR TEPI SUNGAI - MINDFULNESS & KESABARAN) ---
  jala_intro: {
    id: 'jala_intro',
    speaker: 'Bung Jala',
    speakerRole: 'Pemancing Sabar Tepi Sungai',
    portrait: 'fisherman',
    text: 'Ssst... pelan-pelan langkahmu kawan. Lihatlah riak sungai jernih ini... air yang tenang memantulkan langit biru dengan sempurna.',
    thoughtBubble: 'Kesabaran bukanlah sekadar menunggu pasif, melainkan bagaimana kita menjaga hati tetap damai selama menanti.',
    emotionAura: 'tenang',
    choices: [
      {
        id: 'c_jala_patience',
        text: 'Apakah ikannya sudah memakan umpan pancingmu, Bung Jala?',
        impactScore: 10,
        resultDialogueId: 'jala_lesson',
      },
      {
        id: 'c_jala_bored',
        text: 'Apakah kamu tidak bosan duduk berjam-jam di pinggir sungai?',
        impactScore: 5,
        resultDialogueId: 'jala_bored_reply',
      },
    ],
  },
  jala_bored_reply: {
    id: 'jala_bored_reply',
    speaker: 'Bung Jala',
    speakerRole: 'Pemancing Sabar Tepi Sungai',
    portrait: 'fisherman',
    text: 'Haha! Orang yang hanya fokus pada hasil instan akan cepat bosan. Tapi orang yang menikmati suara angin, deburan air, dan tarikan napas akan menemukan ketenangan batin yang mewah.',
    nextId: 'jala_lesson',
  },
  jala_lesson: {
    id: 'jala_lesson',
    speaker: 'Bung Jala',
    speakerRole: 'Pemancing Sabar Tepi Sungai',
    portrait: 'fisherman',
    text: 'Dalam psikologi perkembangan anak, kemampuan menunda kepuasan sesaat demi hasil yang lebih baik disebut "Delayed Gratification". Nah, mari uji kesabaranmu:',
    nextId: 'jala_question',
  },
  jala_question: {
    id: 'jala_question',
    speaker: 'Bung Jala',
    speakerRole: 'Pemancing Sabar Tepi Sungai',
    portrait: 'fisherman',
    text: 'Ketika kamu sedang belajar keterampilan baru (misalnya bermain alat musik, menggambar, atau berhitung) dan belum langsung mahir, apa sikap yang paling bijak?',
    choices: [
      {
        id: 'c_jala_quit',
        text: 'Langsung membanting buku atau pensil karena kesal tidak bisa dalam lima menit pertama.',
        impactScore: 0,
        resultDialogueId: 'jala_wrong',
      },
      {
        id: 'c_jala_persist',
        text: 'Tarik napas teratur, beri diri waktu berlatih rutin setiap hari, dan percaya bahwa setiap tetes usaha akan membuahkan hasil.',
        impactScore: 20,
        unlocksBadge: 'badge_fisherman_patience',
        resultDialogueId: 'jala_reward',
      },
    ],
  },
  jala_wrong: {
    id: 'jala_wrong',
    speaker: 'Bung Jala',
    speakerRole: 'Pemancing Sabar Tepi Sungai',
    portrait: 'fisherman',
    text: 'Kalau kail ditarik sebelum ikan menggigit umpan, pancing akan kusut dan ikan kabur. Begitu pula belajar! Tarik napas hening sejenak, yuk pilih lagi.',
    nextId: 'jala_question',
  },
  jala_reward: {
    id: 'jala_reward',
    speaker: 'Bung Jala',
    speakerRole: 'Pemancing Sabar Tepi Sungai',
    portrait: 'fisherman',
    text: 'Mata kail kesabaranmu sangat tajam! Kamu telah menguasai ketenangan jiwa tingkat tinggi. Terimalah lencana "Pemancing Kesabaran Murni" ini!',
    unlocksBadge: 'badge_fisherman_patience',
    nextId: 'jala_resolved',
  },
  jala_resolved: {
    id: 'jala_resolved',
    speaker: 'Bung Jala',
    speakerRole: 'Pemancing Sabar Tepi Sungai',
    portrait: 'fisherman',
    text: 'Dengarlah gemericik sungai kawan... air selalu menemukan jalannya menembus bebatuan keras bukan dengan kekerasan, melainkan dengan ketekunan tanpa henti.',
    thoughtBubble: 'Hati yang sabar seluas samudra, riak gelombang tak mampu menggoyahkannya.',
    emotionAura: 'tenang',
  },

  // --- RESOLVED DIALOGUES FOR STORYLINE NPCS & MENTORS ---
  kiki_resolved: {
    id: 'kiki_resolved',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Ciiit! Sahabatku! Berkat latihan regulasi emosi dan ketenangan bersamamu, sekarang saat mengantar surat dadaku tidak pernah panik lagi! Air mancur plaza juga jernih berkilau!',
    thoughtBubble: 'Aku tahu sekarang: saat panik datang, aku bisa mempraktikkan teknik ketenangan diri dan meminta bantuan teman!',
    emotionAura: 'gembira',
  },

  ranu_resolved: {
    id: 'ranu_resolved',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu & Penjaga Jembatan',
    portrait: 'old_man',
    text: 'Haha! Selamat datang di jembatan kayu terbaik desa! Jembatan ini sekarang kokoh menghubungkan hati kita semua. Kakek selalu senang melihat kalian melintas!',
    thoughtBubble: 'Aku tak lagi merasa kesepian... anak-anak ini tulus mendengarkan isi hatiku.',
    emotionAura: 'tenang',
  },

  bimo_resolved: {
    id: 'bimo_resolved',
    speaker: 'Bimo',
    speakerRole: 'Murid Pembuat Jam (Kelas 4)',
    portrait: 'boy_glasses',
    text: 'Halo kawan! Aku sudah tidak takut lagi berbuat salah. Kata Pak Joko dan guru, setiap kesalahan adalah petunjuk untuk menjadi lebih pintar dan teliti!',
    thoughtBubble: 'Aku bangga pada diriku sendiri karena berani bangkit dan memperbaiki keadaan!',
    emotionAura: 'gembira',
  },

  tower_resolved: {
    id: 'tower_resolved',
    speaker: 'Nenek Wilis',
    speakerRole: 'Pustakawan Sepuh Desa',
    portrait: 'grandmother',
    text: 'Kalian telah mengembalikan melodi kedamaian di Lembah Nada Rasa. Kabut prasangka musnah seketika saat anak-anak belajar mendengarkan dengan penuh kasih.',
    thoughtBubble: 'Bunga empati telah mekar di sanubari generasi penerus desa kita.',
    emotionAura: 'tenang',
  },

  joko_resolved: {
    id: 'joko_resolved',
    speaker: 'Pak Joko',
    speakerRole: 'Petani Kebun Harapan',
    portrait: 'farmer',
    text: 'Lihat nak! Tanaman sayur di kebun kita tumbuh subur berkat pupuk kesabaran dan usaha tak henti! Ingat selalu filosofi bibit kecil yang tak pernah menyerah!',
    thoughtBubble: 'Senang melihat anak-anak belajar bahwa kegagalan hanyalah batu loncatan menuju keberhasilan.',
    emotionAura: 'gembira',
  },
  pak_joko_intro: {
    id: 'pak_joko_intro',
    speaker: 'Pak Joko',
    speakerRole: 'Petani Kebun Harapan',
    portrait: 'farmer',
    text: 'Halo nak! Masuklah ke kebun! Pagar sengaja kubuka lebar agar kalian bisa melihat kebun sayur ini. Semuanya berawal dari benih mungil yang kita rawat dengan sabar.',
    nextId: 'joko_lesson',
  },
  pak_joko_resolved: {
    id: 'pak_joko_resolved',
    speaker: 'Pak Joko',
    speakerRole: 'Petani Kebun Harapan',
    portrait: 'farmer',
    text: 'Kebun Harapan ini selalu terbuka untuk kalian! Semangat berlatih dan terus pupuk potensi hebat di dalam dirimu ya nak!',
    thoughtBubble: 'Pola pikir berkembang membuat anak-anak tumbuh tangguh seperti pohon beringin.',
    emotionAura: 'gembira',
  },

  citra_resolved: {
    id: 'citra_resolved',
    speaker: 'Kak Citra',
    speakerRole: 'Konselor Cilik Taman Bunga',
    portrait: 'girl_counselor',
    text: 'Bunga-bunga di taman ini mekar dalam harmoni 4 zona warna! Tetaplah sadari perasaanmu setiap saat dan kenali kapan tubuhmu butuh istirahat.',
    thoughtBubble: 'Setiap anak yang mampu mengenali emosinya memiliki lentera penuntun hidup.',
    emotionAura: 'gembira',
  },

  damai_resolved: {
    id: 'damai_resolved',
    speaker: 'Kakek Damai',
    speakerRole: 'Praktisi Mindful & Pohon Bonsai',
    portrait: 'zen_master',
    text: 'Salam damai... Pikiran yang fokus pada hal-hal di dalam kendali diri akan selalu tenang laksana danau tanpa gelombang.',
    thoughtBubble: 'Kedamaian sejati bukan ketiadaan masalah, melainkan ketenangan di tengah riak badai.',
    emotionAura: 'tenang',
  },

  moka_resolved: {
    id: 'moka_resolved',
    speaker: 'Moka',
    speakerRole: 'Kucing Pustakawan Lembut',
    portrait: 'cat_librarian',
    text: 'Purrr... Meow! Telinga yang mau mendengar adalah obat terbaik bagi hati yang sedang gundah. Jadilah pelabuhan aman bagi teman-temanmu ya!',
    thoughtBubble: 'Mendengarkan tanpa menghakimi adalah bentuk kasih sayang yang paling murni.',
    emotionAura: 'tenang',
  },

  kotek_resolved: {
    id: 'kotek_resolved',
    speaker: 'Profesor Kotek',
    speakerRole: 'Ayam Saintis Emosi',
    portrait: 'chicken_glasses',
    text: 'KUKU-RUYUK! Sensor endorfinku mendeteksi kadar kebahagiaan 100% di seluruh desa! Teruslah tersenyum dan sebarkan tawa ceria!',
    thoughtBubble: 'Kokok ceriaku hari ini dijamin menurunkan hormon stres siapa pun yang mendengarnya!',
    emotionAura: 'gembira',
  },

  // --- FREE ROAM LIVING WORLD OBJECTS ---
  free_roam_windmill: {
    id: 'free_roam_windmill',
    speaker: 'Kincir Angin Harmoni',
    speakerRole: 'Ikon Dinamisme Pedesaan',
    portrait: 'clock',
    text: 'Kincir angin pedesaan berputar anggun tertiup semilir angin sore. Bilah-bilah kayunya berderit tenang, menggiling gandum emas Pak Joko menjadi tepung harum untuk hidangan seluruh warga.',
    thoughtBubble: 'Angin sepoi-sepoi membawa kesegaran dan harmoni ke seluruh penjuru lembah.',
    emotionAura: 'tenang',
  },

  free_roam_cow: {
    id: 'free_roam_cow',
    speaker: 'Sapi Padang Rumput',
    speakerRole: 'Penghuni Padang Hijau',
    portrait: 'cow',
    text: 'Moo-ooh! Sapi perah bertubuh sehat ini mengunyah rumput segar dengan santai, ekornya mengibas ramah mengusir lalat. Kehadirannya menghadirkan ketenangan pedesaan yang alami.',
    thoughtBubble: 'Rumput hari ini terasa manis dan renyah... Hidup di lembah damai sungguh menyenangkan.',
    emotionAura: 'tenang',
  },

  free_roam_sheep: {
    id: 'free_roam_sheep',
    speaker: 'Domba Wol Putih',
    speakerRole: 'Penghuni Padang Hijau',
    portrait: 'sheep',
    text: 'Mbeee~ Domba berbulu lebat dan seputih awan ini menatapmu dengan mata bulat yang bersahabat. Membelai bulunya yang lembut memberikan rasa tenang dan relaksasi.',
    thoughtBubble: 'Padang rumput lembah kini begitu hangat dan hijau tanpa kabut kelabu.',
    emotionAura: 'gembira',
  },

  free_roam_deer: {
    id: 'free_roam_deer',
    speaker: 'Rusa Tutul Hutan',
    speakerRole: 'Sahabat Rimba Tenang',
    portrait: 'deer',
    text: 'Rusa tutul yang anggun ini melangkah tenang dari tepian hutan pinus menuju padang rumput. Telinganya bergerak waspada namun matanya memancarkan rasa damai dan percaya.',
    thoughtBubble: 'Hutan kini terasa begitu sejuk dan aman. Tak ada lagi kabut kelabu yang membuat cemas.',
    emotionAura: 'tenang',
  },

  free_roam_rabbit: {
    id: 'free_roam_rabbit',
    speaker: 'Kelinci Padang Rumput',
    speakerRole: 'Penjelajah Semanggi',
    portrait: 'rabbit',
    text: 'Hidung merah muda kelinci mungil ini kembang kempis cepat saat mengendus daun semanggi segar. Ia melompat riang di dekat kawanan domba, menikmati kebebasan di alam terbuka.',
    thoughtBubble: 'Semanggi di sini paling manis! Lompat ke sana, lompat ke sini... senangnya!',
    emotionAura: 'gembira',
  },

  free_roam_lamb: {
    id: 'free_roam_lamb',
    speaker: 'Anak Domba Gemas',
    speakerRole: 'Penghuni Baru Padang Hijau',
    portrait: 'lamb',
    text: 'Mbee-ee! Anak domba kecil berbulu seputih kapas ini melonjak-lonjak lincah di samping induknya, ekor kecilnya bergoyang ceria penuh kegembiraan.',
    thoughtBubble: 'Ibu domba ada di dekatku, rumputnya empuk, dan harinya cerah!',
    emotionAura: 'gembira',
  },

  free_roam_squirrel: {
    id: 'free_roam_squirrel',
    speaker: 'Tupai Hutan',
    speakerRole: 'Pengumpul Biji Pinus',
    portrait: 'squirrel',
    text: 'Tupai lincah berbuntut lebat ini duduk di atas batas hutan sambil menggenggam buah pohon ek dengan kedua cakar kecilnya. Pipinya menggembung menggemaskan.',
    thoughtBubble: 'Kacang ek ini simpanan musim semi! Lembah yang pulih menyediakan makanan berlimpah.',
    emotionAura: 'gembira',
  },

  free_roam_river: {
    id: 'free_roam_river',
    speaker: 'Aliran Sungai Jernih',
    speakerRole: 'Kehidupan Air Lembah',
    portrait: 'fountain',
    text: 'Air sungai mengalir jernih berkilauan. Sekumpulan ikan kecil berenang lincah melawan arus lembut, menciptakan riak-riak air melingkar di dekat dermaga Bung Jala.',
    thoughtBubble: 'Gemercik air yang hidup membangkitkan kesegaran indra dan ketenangan batin.',
    emotionAura: 'tenang',
  },

  free_roam_waterfall: {
    id: 'free_roam_waterfall',
    speaker: 'Air Terjun Sungai Harmoni',
    speakerRole: 'Kesejukan Air Lembah',
    portrait: 'fountain',
    text: 'Gemuruh air terjun bertingkat berpadu indah dengan gemercik busa putih yang membentur batuan cadas sungai di dekat jembatan. Uap air segar dan percikan embun melayang lembut di udara, membawa rasa damai dan kesegaran batin.',
    thoughtBubble: 'Arus emosi mengalir deras layaknya air terjun; kita tidak perlu menahannya, cukup sadari dan biarkan ia mengalir dengan tenang.',
    emotionAura: 'tenang',
  },
};
